dist: trusty
language: java
addons:
  apt:
    packages:
    - chromium-browser
install:
  - mvn --settings travis-maven-settings.xml help:effective-settings
  - mvn --settings travis-maven-settings.xml dependency:resolve
script: mvn --settings travis-maven-settings.xml verify -B
