dist: trusty
language: java
install:
  - mvn -B --settings travis-maven-settings.xml -Ptravis dependency:resolve dependency:resolve-plugins
script:
  - mvn -B --settings travis-maven-settings.xml -Ptravis verify
