dist: trusty
language: java
addons:
  apt:
    packages:
    - chromium-browser
    - fakeroot
notifications:
  email: false
before_install:
  - dpkg-query -l chromium-browser
install: true
script:
  - mvn -B --settings travis-maven-settings.xml -Ptravis -Dhar-replay.chromedriver.version=$CHROMEDRIVER_VERSION install
