dist: trusty
language: java
install:
  - mvn -B --settings travis-maven-settings.xml dependency:resolve
  - mvn -B --settings travis-maven-settings.xml dependency:resolve-plugins
script:
  - mvn -B --settings travis-maven-settings.xml verify -Dhar-replay.chromedriver.chrome.arguments=--no-sandbox
