dist: trusty
language: java
notifications:
  email: false
install: true
script:
  - mvn -B --settings travis-maven-settings.xml -Ptravis -Dhar-replay.chromedriver.version=$CHROMEDRIVER_VERSION install
