version: "{build}"
image: Visual Studio 2017
environment:
  PYTHON: "C:\\Python36-x64"
  PYTHON_VERSION: 3.6
  PYTHON_ARCH: 64
build_script:
- cmd: >-
    set JAVA_HOME=C:\Program Files\Java\jdk1.8.0

    mvn --version

    python --version

    echo "environment: PYTHON=%PYTHON%"

    echo "environment: GITHUB_TOKEN_NAME=%GITHUB_TOKEN_NAME%"

    echo "environment: CHROMEDRIVER_VERSION=%CHROMEDRIVER_VERSION%"

    echo "environment: MAVEN_OPTIONS=%MAVEN_OPTIONS%"

    mvn install %MAVEN_OPTIONS% --batch-mode -Dwdm.chromeDriverVersion=%CHROMEDRIVER_VERSION% -Dwdm.gitHubTokenName=%GITHUB_TOKEN_NAME% -Dwdm.gitHubTokenSecret=%GITHUB_TOKEN_SECRET%
